// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9Wy82YTxzC27FO7vuCpjb0eL31EAF8k',
    appId: '1:863281278979:web:7fbb92f1994de86d489e36',
    messagingSenderId: '863281278979',
    projectId: 'homework-tracker-3541',
    authDomain: 'homework-tracker-3541.firebaseapp.com',
    storageBucket: 'homework-tracker-3541.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5YSm3faKg_YegTYjZweezoD5-_s-kucc',
    appId: '1:863281278979:android:7d4bc1718d5e8857489e36',
    messagingSenderId: '863281278979',
    projectId: 'homework-tracker-3541',
    storageBucket: 'homework-tracker-3541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPyOfUf1Dm_qejXDzL0lPwDud1UkKxR8',
    appId: '1:863281278979:ios:821c03b67a9ade15489e36',
    messagingSenderId: '863281278979',
    projectId: 'homework-tracker-3541',
    storageBucket: 'homework-tracker-3541.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPyOfUf1Dm_qejXDzL0lPwDud1UkKxR8',
    appId: '1:863281278979:ios:821c03b67a9ade15489e36',
    messagingSenderId: '863281278979',
    projectId: 'homework-tracker-3541',
    storageBucket: 'homework-tracker-3541.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd9Wy82YTxzC27FO7vuCpjb0eL31EAF8k',
    appId: '1:863281278979:web:70ac300f7c938103489e36',
    messagingSenderId: '863281278979',
    projectId: 'homework-tracker-3541',
    authDomain: 'homework-tracker-3541.firebaseapp.com',
    storageBucket: 'homework-tracker-3541.firebasestorage.app',
  );
}
